name: Build-min_stage1

on:
  pull_request:
  push:
  schedule:
    - cron: '13 7,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        MATRIX_CODE_NAME: ['bookworm', 'trixie', 'sid']

    env:
      CODE_NAME: ${{ matrix.MATRIX_CODE_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: bash min-stage1-$CODE_NAME.sh

      - name: Log in to the Docker container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # if: ${{ github.ref == 'refs/heads/main' }}

      - name: Publish the Docker image
        run: source tmp/bin/set-variables && docker push $DOCKER_IMAGE:latest
        # if: ${{ github.ref == 'refs/heads/main' }}

      - name: Delete containers older than a minute
        uses: snok/container-retention-policy@v2
        with:
          # image-names: image-debian-bookworm-min-stage1, image-debian-trixie-min-stage1, image-debian-sid-min-stage1
          image-names: 'image-debian-'+os.environ['CODE_NAME']+'-min-stage1'
          cut-off: A minute ago UTC
          account-type: org
          org-name: nosurprisedev
          keep-at-least: 2
          token: ${{ secrets.SPECIAL_TOKEN }}
        # if: ${{ github.ref == 'refs/heads/main' }}

      - name: Log out of the Docker container registry
        run: docker logout ghcr.io
        # if: ${{ github.ref == 'refs/heads/main' }}
